# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-05 14:04
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='BeautyGroupResult',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
