# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-05 17:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0003_auto_20190305_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='CurrentAnswersById',
            field=django.contrib.postgres.fields.ArrayField(base_field=otree.db.models.IntegerField(null=True), null=True, size=3),
        ),
    ]
