# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-25 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0004_group_currentanswersbyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='BeautyGroupResult',
        ),
        migrations.RemoveField(
            model_name='group',
            name='CurrentAnswersById',
        ),
        migrations.RemoveField(
            model_name='player',
            name='BeautyChangeHistory',
        ),
        migrations.RemoveField(
            model_name='player',
            name='BeautyCurrentAnswer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='BeautyFirstAnswer',
        ),
    ]
