# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-06 10:04
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimebasiccode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='BeautyGroupResult',
        ),
        migrations.RemoveField(
            model_name='group',
            name='CurrentAnswersById',
        ),
        migrations.RemoveField(
            model_name='group',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='group',
            name='price',
        ),
        migrations.RemoveField(
            model_name='player',
            name='BeautyChangeHistory',
        ),
        migrations.RemoveField(
            model_name='player',
            name='BeautyCurrentAnswer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='BeautyFirstAnswer',
        ),
        migrations.AddField(
            model_name='group',
            name='my_group_chr_variable',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='my_group_int_variable',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='my_player_chr_variable',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='my_player_int_variable',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
