# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-06 12:25
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimebasiccode', '0003_auto_20190306_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='my_player_chr_variable',
            field=otree.db.models.StringField(default='', max_length=10000, null=True),
        ),
    ]
