# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-06 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtimebasiccode', '0004_auto_20190306_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='my_player_chr_variable',
        ),
    ]
