# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-06 15:43
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimebasiccode', '0006_remove_group_my_group_chr_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='my_group_int_variable',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
